### ISSUE TITLE
Does it work with timefree 30 now?

### ISSUE THREAD

**Issue by cykac04** [garret1317/yt-dlp-rajiko#22]
I have tried to pass cookies by cookie.txt and browser but it still said the cookies not work.

`yt-dlp "https://radiko.jp/#!/ts/802/20241025170000" --cookies "C:\Users\User\Documents\radiko.txt"
[RadikoTimeFree] Extracting URL: https://radiko.jp/#!/ts/802/20241025170000
[RadikoTimeFree] 802: Downloading programme data
ERROR: [RadikoTimeFree] 20241025170000: Programme is only available with a Timefree 30 subscription. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies`

**Comment by garret1317** [comment]
No, it doesn't work at the minute, sorry.
I put the code to handle it there half-finished, for me to complete later once I'd figured out how to handle the login etc
and then when it's done I'd make a release with the working version. I wasn't expecting anyone to be running off the master branch...

**Comment by garret1317** [comment]
d84e4dbe4f4b1be71e17072dc2a2f3685b9a2997
give this a go, should work

note that the usual on-demand stream provider doesn't have timefree30 stuff, so we have to use one that streams it as-live
so you can only download in real-time unfortunately ("record" would be the better word i guess)

**Comment by cykac04** [comment]
I have found your commit in yt-dlp and it works like this.
Is that extractor still not work properly yet?

> yt-dlp "https://radiko.jp/#!/ts/802/20241025170000" --cookies radiko.txt
> [Radiko] Extracting URL: https://radiko.jp/#!/ts/802/20241025170000
> [Radiko] Checking account status from cookies
> [Radiko] 802: Downloading programme information for 20241025
> [Radiko] Checking cached token
> [Radiko] 802-20241025170000: Downloading stream information
> [Radiko] 802-20241025170000: Downloading m3u8 information from tf-f-rpaa-radiko.smartstream.ne.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from tf-c-rpaa-radiko.smartstream.ne.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from radiko.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> ERROR: [Radiko] 802-20241025170000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by garret1317** [comment]
clear your yt-dlp cache (`--rm-cache-dir`), it's using an old auth token from when you weren't signed in
then it should work
but yeah as you can see it's still a bit rough around the edges

**Comment by cykac04** [comment]
Still 403 error. Should I share the account to you?

> yt-dlp "https://radiko.jp/#!/ts/802/20241025170000" --rm-cache-dir --username "***" --password "***"
> Removing cache dir C:\Users\ADMIN/.cache\yt-dlp ...
> [Radiko] Logging in
> [Radiko] Extracting URL: https://radiko.jp/#!/ts/802/20241025170000
> [Radiko] 802: Downloading programme information for 20241025
> [Radiko] Downloading authentication page
> [Radiko] Downloading player js code
> [Radiko] Authenticating
> [Radiko] 802-20241025170000: Downloading stream information
> [Radiko] 802-20241025170000: Downloading m3u8 information from tf-f-rpaa-radiko.smartstream.ne.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from tf-c-rpaa-radiko.smartstream.ne.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> [Radiko] 802-20241025170000: Downloading m3u8 information from radiko.jp
> WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
> ERROR: [Radiko] 802-20241025170000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by garret1317** [comment]
i might be able to diagnose with a verbose log from the plugin
but sure, send to garret1317@yandex.com or garret1317 on discord

**Comment by garret1317** [comment]
per discussion on discord:
my patch for yt-dlp proper doesn't work with areafree, because it's requesting with `type=b` (seems to be only for in-area), but it should be using `type=c` (seems to be for areafree)
https://github.com/yt-dlp/yt-dlp/pull/11498#issuecomment-2493782013
plugin works because it always sets itself to be in area

**Comment by garret1317** [comment]
timefree 30 support is in v1.2 now

**Comment by jackyzy823** [comment]
> note that the usual on-demand stream provider doesn't have timefree30 stuff, so we have to use one that streams it as-live
so you can only download in real-time unfortunately ("record" would be the better word i guess)

Hi, some one provided me a premium account cookie , so i can do some test on this. the timeshift endpoint only returns `l` (the url param `l` ) seconds aac urls per request. (sadly the https://radiko.jp/v2/api/ts/playlist.m3u8  endpoint not work for tf30)

so I've got an idea , request with `seek=seek+l` and `l=300` (the max value) until `seek` > `end_at` to gather all aac urls. 

And then 1) generate a m3u8 contains these aac for ffmpeg to download and convert  or 2)  return the array of aac urls for ffmpeg to download and convert.

I'm not sure which method does yt-dlp support. 

I've seen someone asked the method 1 in https://github.com/yt-dlp/yt-dlp/issues/8503


-----------------------
off-topic:

I've encounter some radio program which will expire soon for 7 days.  but the timeshift endpoint returns 400  (i think this endpoint should always work),  and https://radiko.jp/v2/api/ts/playlist.m3u8  endpoint could download.
